version: "3"
networks: 
    network:
        driver: ${NETWORKS_DRIVER}
services:
    php-fpm74:
        image: php:7.4-fpm
        environment:
            - OPCACHE_ENABLE=${OPCACHE_ENABLE}
            - OPCACHE_ENABLE_CLI=${OPCACHE_ENABLE_CLI}
        container_name: php-fpm74
        build: .\php-fpm\
        restart: unless-stopped
        networks:
            - network
        volumes:
            - ${MOUNT_SOURCE}:${MOUNT_TARGET}
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
                - MYSQL_USER=${MYSQL_USER}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_LOCAL_PORT}:3306
        restart: always
        volumes:
            - ${MYSQL_LOCAL_DATA}:/var/lib/mysql
        networks:
            - network
    go:
        build: ./go
        volumes:
            - ${MOUNT_SOURCE}:${MOUNT_TARGET}
        networks:
            - network
    node:
        build:
            context:  ./node
            args:
                - NODE_VERSION=${NODE_VERSION}
        volumes:
            - ${MOUNT_SOURCE}:${MOUNT_TARGET}
        networks:
            - network
